services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nodejs_crud
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    volumes:
      - ./gcp-key.json:/app/gcp-key.json:ro
    image: nodejs-crud
    depends_on:
      - db
    ports:
      - "3000:3000"
    env_file:
      - .env.docker

volumes:
  postgres_data:
